name: hrm_saas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  http: ^1.2.2
  intl: ^0.20.2
  network_info_plus: ^7.0.0
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.4
  pdf: ^3.11.3
  printing: ^5.14.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/hrm_logo.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/hrm_logo.png
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/images/
